format = """
[î‚¶](#9A348E)\
[î‚°](bg:#DA627D fg:#9A348E)\
$directory\
[î‚°](fg:#DA627D bg:#FCA17D)\
$git_branch\
[î‚°](fg:#FCA17D bg:#86BBD8)\
$c\
$elixir\
$elm\
$golang\
$gradle\
$haskell\
$java\
$julia\
$nodejs\
$python\
$nim\
$rust\
$scala\
[î‚°](fg:#86BBD8 bg:#06969A)\
$docker_context\
[î‚°](fg:#06969A bg:#33658A)\
$time\
[î‚° ](fg:#33658A)\
$fill\
$cmd_duration\
$conda\
$line_break\
$character\
"""

# Disable the blank line at the start of the prompt
# add_newline = true

[character]
success_symbol = "[âœ](blue)"

# An alternative to the username module which displays a symbol that
# represents the current operating system
[os]
style = "bg:#9A348E"
disabled = true # Disabled by default

[fill]
symbol  = " "

[conda]
format = "[$symbol$environment]($style) "
style = "gray"

[cmd_duration]
min_time = 10_000
format = "[$symbol$duration]($style) "
style = "gray"

[directory]
format = "[$path]($style)(bold blue)[$read_only](bold #F0FF42)"
truncation_length = 2
truncation_symbol = 'â€¦/'
home_symbol = " ï€• "
style = "bg:#DA627D fg:black"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = "ó°ˆ™ "
"Downloads" = "ï€™ "
"Music" = "ï€ "
"Pictures" = "ï€¾ "
# Keep in mind that the order matters. For example:
# "Important Documents" = " ó°ˆ™ï„ª "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important ó°ˆ™ " = " ó°ˆ™ï„ª "

[c]
symbol = "î˜ "
style = "bg:#86BBD8 fg:black"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = "ïŒˆ "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[elixir]
symbol = "î‰µ "
style = "bg:#86BBD8 fg:black"
format = '[ $symbol ($version) ]($style)'

[elm]
symbol = "î˜¬ "
style = "bg:#86BBD8 fg:black"
format = '[ $symbol ($version) ]($style)'

[git_branch]
symbol = "ï˜"
style = "bg:#FCA17D fg:black"
format = '[ $symbol $branch ]($style)'

[git_status]
disabled = true
style = "bg:#FCA17D"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = "ğŸ¹ "
style = "bg:#86BBD8 fg:black"
format = '[ $symbol ($version) ]($style)'
not_capable_style = "bg:#86BBD8 fg:red"

[gradle]
style = "bg:#86BBD8 fg:black"
format = '[ $symbol ($version) ]($style)'

[haskell]
symbol = "î· "
style = "bg:#86BBD8 fg:black"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = "î‰– "
style = "bg:#86BBD8 fg:black"
format = '[ $symbol ($version) ]($style)'

[julia]
symbol = "î˜¤ "
style = "bg:#86BBD8 fg:black"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = "îœ˜"
style = "bg:#86BBD8 fg:black"
format = '[ $symbol ($version) ]($style)'

[nim]
symbol = "ó°†¥ "
style = "bg:#86BBD8 fg:black"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = "î¨"
style = "bg:#86BBD8 fg:black"
format = '[ $symbol ($version) ]($style)'

[scala]
symbol = "îœ· "
style = "bg:#86BBD8 fg:black"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#33658A"
format = '[ ïº $time ]($style)'

[python]
symbol = "ğŸ "
style = "bg:#86BBD8 fg:black"
format = '[ $symbol ($version) ]($style)'
